const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.video,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.Arr,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Arr.Acts.SplitString,
		C3.Plugins.Arr.Acts.Shuffle,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor2,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Acts.Delete,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.video.Acts.SetPlaybackTime,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.video.Acts.SetVisible,
		C3.Plugins.video.Cnds.CompareInstanceVar,
		C3.Plugins.video.Acts.Play,
		C3.Plugins.video.Cnds.HasEnded,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.video.Cnds.IsPlaying,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{videoIndex: 0},
	{Video1: 0},
	{oldPosY: 0},
	{newPosY: 0},
	{Tween: 0},
	{menuBg: 0},
	{posX: 0},
	{posY: 0},
	{itemIndex: 0},
	{su: 0},
	{etilenGlikol: 0},
	{gliserin: 0},
	{Touch: 0},
	{refreshBtn: 0},
	{audioBtn: 0},
	{shareBtn: 0},
	{fullScreenBtn: 0},
	{Browser: 0},
	{loaderEmpty: 0},
	{loaderFill: 0},
	{loaderLogo: 0},
	{Video2: 0},
	{Video3: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{videoBg: 0},
	{videoArray: 0},
	{playBtn: 0},
	{isActive: 0},
	{prevBtn: 0},
	{nextBtn: 0},
	{Mouse: 0},
	{Audio: 0},
	{yonerge: 0},
	{menuItems: 0},
	{videos: 0},
	{videoBtn: 0},
	{animStart: 0},
	{showKulpOutline: 0},
	{showMenuItemOutline: 0},
	{showDereceOutline: 0},
	{showVideoMenu: 0},
	{videoStart: 0},
	{activeItemIndex: 0},
	{activeLayer: 0},
	{timeCount: 0},
	{timeStart: 0},
	{isLoader: 0}
];

self.InstanceType = {
	Video1: class extends self.IWorldInstance {},
	menuBg: class extends self.ISpriteInstance {},
	su: class extends self.ISpriteInstance {},
	etilenGlikol: class extends self.ISpriteInstance {},
	gliserin: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	refreshBtn: class extends self.ISpriteInstance {},
	audioBtn: class extends self.ISpriteInstance {},
	shareBtn: class extends self.ISpriteInstance {},
	fullScreenBtn: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	loaderEmpty: class extends self.ISpriteInstance {},
	loaderFill: class extends self.ISpriteInstance {},
	loaderLogo: class extends self.ISpriteInstance {},
	Video2: class extends self.IWorldInstance {},
	Video3: class extends self.IWorldInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	videoBg: class extends self.ISpriteInstance {},
	videoArray: class extends self.IArrayInstance {},
	playBtn: class extends self.ISpriteInstance {},
	prevBtn: class extends self.ISpriteInstance {},
	nextBtn: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	yonerge: class extends self.ISpriteInstance {},
	menuItems: class extends self.ISpriteInstance {},
	videos: class extends self.IWorldInstance {},
	videoBtn: class extends self.ISpriteInstance {}
}